name: Frontend feature request
description: Request a new feature in Frontend.
title: "[FEATURE] "
type: feature
projects: ["Data-Science-Club-TEC/1"]
body:
  - type: input
    id: todo_summary
    attributes:
      label: TODO (Summary)
      description: A 15 to 25 word synthesis on what needs to be done.
      placeholder: Write a concise synthesis of the task...
    validations:
      required: true

  - type: textarea
    id: scope_of_work
    attributes:
      label: Scope of Work
      description: Detailed explanation of the feature and requirements.
      placeholder: Provide full technical details, acceptance criteria, and user stories...
    validations:
      required: true
