name: Frontend feature request
description: Request a new feature in Frontend.
title: "[FEATURE]: "
labels: ["feature"]
projects: ["Data-Science-Club-TEC/1"]
body:
  - type: textarea
    id: todo
    attributes:
      label: TODO
      value: |
        Let's see if y'all can cook a Figma for the page!
    validations:
      required: true

  - type: textarea
    id: scope_of_work
    attributes:
      label: Scope of Work
      value: |
        As title explains, we need a better figma than the one made by the previous generation. Make two Figmas, one for Light mode and another one for Dark mode.
    validations:
      required: true